<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="principalInvestigators.aspx.cs" Inherits="InternTestProject.principalInvestigators" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView runat="server" ID="piGrid"
        ItemType="InternTestProject.Models.Investigator"
        DataKeyNames="PI_ID"
        SelectMethod="piGrid_GetData"
        UpdateMethod="piGrid_UpdateItem" DeleteMethod="piGrid_DeleteItem"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
        AutoGenerateColumns="false">
        <Columns>
            <asp:DynamicField DataField="PI_ID" />
            <asp:DynamicField DataField="FirstName" />
            <asp:DynamicField DataField="LastName" />
            <asp:DynamicField DataField="Institution" />
            <asp:DynamicField DataField="Research" />
        </Columns>
    </asp:GridView>
</asp:Content>
